name       : xdelta3
version    : 3.0.11
release    : 1
source     :
    - https://github.com/jmacd/xdelta/archive/v3.0.11.tar.gz : 28278a4d73127f3d2b00bbde179f8ee1f289ccd3f7f2ac7cd837f6580f90a7b7
license    : Apache-2.0
component  : system.utils
summary    : Xdelta is a tool and library for differential compression.
description: |
    Xdelta is a tool and library for differential compression.
setup      : |
    pushd xdelta3
    %reconfigure
    popd
build      : |
    pushd xdelta3
    %make
    popd
install    : |
    pushd xdelta3
    %make_install
    popd
